# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - client

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseNode@1
  displayName: 'Setup node.js'
  inputs:
    version: '12.13.0'
- script: |
    cd ./client
    npm install
    npm run buildDev
  displayName: 'Build client bundle'
- task: CopyFiles@2
  inputs:
    SourceFolder: './static'
    Contents: 'bundle.js'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'bundle.js'
    publishLocation: 'Container'
